name: release-to-stage

on:
  push:
    tags:
    - "rc"
    
permissions:
  contents: write
  pull-requests: write


jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: ev.com
          pull-request-title-pattern: 'chore: release ${version} to stage env'
          default-branch: release/stage/ca
